### ISSUE TITLE
test

### ISSUE THREAD

**Issue by resmo** [resmo/ansible-role-bind#18]

**Comment by elrido** [comment]
Dear René,

Was there any reason you know of why the resmo.bind role was removed from ansible galaxy? Should I stop using it?

Best regards,
Simon

**Comment by resmo** [comment]
Thanks for reporting. I had no clue it was removed. 

I synced again and now they are available again. can you confirm?

**Comment by elrido** [comment]
Yes its there again including all its history:
https://galaxy.ansible.com/resmo/bind/

Thank you very much for sharing your work! I'm using this role for two environments already.
